baseURL = "https://jaymickey.github.io"
languageCode = "en-us"
title = "Josh M. - DevOps Engineer"
theme = "even"
enableRobotTXT = true
enableEmoji = true

copyright = "Josh Michielsen"

[author]
  name = "Josh Michielsen"

[params]
  since = "2018"
  logoTitle = "Josh M."

[params.social]
  a-email = "mailto:me@joshm.io"
