baseURL = "https://jaymickey.github.io"
title = "Josh Michielsen (Jmickey)"
theme = "minimo"
copyright = ""
enableRobotsTXT = true
defaultContentLanguage = "en"
Paginate = 10
preserveTaxonomyNames = true
pygmentsCodefences = true

[params.settings]
  dateFormat = "2006, Jan 02"
  listDateFormat = "2006, Jan 02"

[params.social]
  github = "jaymickey"
  linkedin = "jmichielsen"
  twitter = "jmickey_"
  email = "josh@jmickey.io"

[params.social.config]
  platforms = ["linkedin", "github", "twitter", "email"]

[params.info]
  description = "DevOps Engineer @ Bankwest. CompSci & Data Science student @ UNE. Passionate about DevOps, Continuous Delivery, Infrastructure as Code, and Software Development (Python, C#, Scala, and soon - Golang)"
  title404 = "Nothing's here!"

[params.copyright]
  prefix = ""
  holder = "Josh Michielsen"
  startYear = "2018"
  suffix = ""

[params.widgets]
  homepage = ["recent_posts"]
  sidebar = ["about", "social_menu"]

[params.sidebar]
  enable = true
  sticky = true

[taxonomies]
  author = "authors"

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
