baseURL = "https://mickey.dev"
title = "Josh Michielsen (Jmickey)"
theme = "KeepIt"
copyright = "2019 Josh Michielsen"
enableEmoji = true
enableRobotsTXT = true
defaultContentLanguage = "en"
Paginate = 10
preserveTaxonomyNames = true
pygmentsCodefences = true

[author]
  name = "jmickey"

  [params.publisher]
    name = "jmickey"

    [params.publisher.logo]
      url = "images/logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "images/logo.png"
    width = 127
    height = 40

[Permalinks]
 posts = "/posts/:slug"

 [menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[params]
  author = "Josh Michielsen"
  subtitle = "Platform Engineer, Go, Kubernetes, Photography, Coffee"
  description = "Aussie 🇦🇺 in Cambridge 🇬🇧. Senior Software Engineer, Cloud Platform @ Condé Nast International. Previously Bankwest. #doge owner. Photographer 📷"
  socialShare = true

[params.gravatar]
    email = "j@mickey.dev"

[params.social]
  Github = "jaymickey"
  Linkedin = "jmichielsen"
  Twitter = "jmickey_"
  Email = "j@mickey.dev"
  Strava = "32368360"
  Keybase = "jmickey"

[params.share]
  Twitter = true
  Linkedin = true

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
