baseURL = "https://jaymickey.github.io"
title = "Josh Michielsen (Jmickey)"
theme = "minimo"
copyright = ""
enableRobotsTXT = true
defaultContentLanguage = "en"
Paginate = 10
preserveTaxonomyNames = true
pygmentsCodefences = true

[params.social]
  github = "jaymickey"
  twitter = "jmickey_"
  email = "josh@jmickey.io"
  linkedin = "jmichielsen"

[params.social.config]
  platforms = ["linkedin", "github", "twitter", "email"]

[params.info]
  description = "DevOps Engineer @ Bankwest by day. CompSci & Data Science student by night. Passionate about DevOps, Continuous Delivery, Infrastructure as Code, and Software Development"
  title404 = "Nothing's here!"

[params.copyright]
  prefix = ""
  holder = "Josh Michielsen"
  startYear = "2018"
  suffix = ""

[params.settings]
  recentPostsLength = 4
  homepageSections = ["recent_posts"]

[taxonomies]
  author = "authors"

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
