[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.55.5"
  HUGO_ENV = "staging"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --gc --minify -b ${URL}/"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -b ${DEPLOY_PRIME_URL}/"

[context.branch-deploy]
  command = "hugo -b ${DEPLOY_PRIME_URL}/"